name: Create weekly issues
on:
  schedule:
    - cron: 0 0 * * 0
  workflow_dispatch: {}

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  create_issue:
    name: Create weeksly issues
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - run: |
          gh issue create --repo "openedx/axim-engineering" \
            --title "Welcome new discourse members" \
            --label "github-request" \
            --body "Go through [new discourse introductions](https://discuss.openedx.org/c/community/introductions/18) and welcome new people to the community."
