name: Create weekly issues
on:
  schedule:
    - cron: 0 11 * * 2
  workflow_dispatch: {}

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  ORGANIZATION: openedx

jobs:
  create_issue:
    name: Create weekly issues
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - run: |
          gh issue create --repo "openedx/axim-engineering" \
            --title "Welcome new discourse members" \
            --label "github-request" \
            --body "Go through [new discourse
            introductions](https://discuss.openedx.org/c/community/introductions/18)
            and welcome new people to the community."
          gh issue comment "$new_issue_url" \
            --body "@openedx/axim-oncall heads up on this request"
